name: Pull Request review notification

on:
  pull_request_review:
    types: [submitted]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event.review.state != 'commented'
    steps:
      - uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "PR: *<${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>*\ncomment by ${{ github.event.review.user.login }}\n\n${{ github.event.review.state }}\n\n${{ github.event.review.body }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
